defaults: &defaults
  working_directory: ~/drunk-jesus-mobile
  docker:
    - image: circleci/node

caches:
  - &yarn_cache drunk-jesus-mobile-v1{{ checksum "yarn.lock" }}

references:
  restore_yarn_cache: &restore_yarn_cache
    restore_cache:
      keys:
        - *yarn_cache

  yarn_install: &yarn_install
    run:
        name: Installing packages
        command: yarn install

  save_yarn_cache: &save_yarn_cache
    save_cache:
      name: Save Yarn Package Cache
      key: *yarn_cache
      paths:
        - ~/.cache

version: 2

jobs:
  linters:
    <<: *defaults

    steps:
      - checkout

      - <<: *restore_yarn_cache
      - <<: *yarn_install
      - <<: *save_yarn_cache

      - run:
          name: Running linters
          command: yarn lint

  tests:
    <<: *defaults

    steps:
      - checkout

      - <<: *restore_yarn_cache
      - <<: *yarn_install
      - <<: *save_yarn_cache

      - run:
          name: Running tests
          command: yarn test:circle

      - store_artifacts:
          name: Saving Jest coverage
          path: ~/drunk-jesus-mobile/coverage/lcov-report
          destination: /jest-coverage

  e2e:
    <<: *defaults

    steps:
      - checkout

      - <<: *restore_yarn_cache
      - <<: *yarn_install
      - <<: *save_yarn_cache

      - run:
          name: Build android bundle
          command: yarn detox:build:android

workflows:
  version: 2
  build:
    jobs:
      - linters
      - tests
      - e2e
